@hostname = localhost
@port = 3000

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "eu@teste.com",
  "password": "eu lucas"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "eu@teste.com",
  "password": "eu lucas"
}