@port = {{$processEnv port}}
### POST /api/auth/register
# @name i
POST http://{{hostname}}:{{port}}/api/auth/register
Content-Type: application/json

{
  "email": "eu@teste.com",
  "password": "eu lucas"
}
###
@email = {{i.request.body.email}}
@password = {{i.request.body.password}}
###
POST http://{{hostname}}:{{port}}/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}