@id = 0

### get produtos
GET http://{{hostname}}:{{port}}/api/produtos/{{id}}

### POST produtos
# @name createProduct
# @prompt description
# @prompt price
POST http://{{hostname}}:{{port}}/api/produtos/
Content-Type: application/json

{
  "description": "{{description}}",
  "price": {{price}}
}

###

@id = {{createProduct.response.body.$.produto.$.id}}

###
# @prompt description
PUT http://{{hostname}}:{{port}}/api/produtos/{{id}}
Content-Type: application/json

{
  "description": "{{description}}",
  "price": 33
}

###
DELETE http://{{hostname}}:{{port}}/api/produtos/{{id}}