@hostname = localhost
@port = 3000

GET http://{{hostname}}:{{port}}/api/user/me/?id=177422283417
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc3NDIyMzI4MzQxNywiaWF0IjoxNzc0MjIzMjg2LCJleHAiOjE3NzQyMjY4ODZ9.LDknP7NIW1XVyN2hEwuDtKduH7j4F0eOBjbooBDSN9M
Content-Type: application/json
