@id = 1774459790484

### GET Meu usuário
# @name getMe
GET http://{{hostname}}:{{port}}/api/user/me/?id=123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc3NDQ1OTc5MDQ4NCwiaWF0IjoxNzc0NDU5Nzk0LCJleHAiOjE3NzQ0NjMzOTR9.Cqe_Px-zilxWUM6gSsw3mMDIKKNrgEx8RWtz2-fUfZ8