@hostname = localhost
@port = 3000

GET http://{{hostname}}:{{port}}/api/user/me/1774068303946
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTc3NDA2ODMwMzk0NiwiaWF0IjoxNzc0MDY4MzEwLCJleHAiOjE3NzQwNzE5MTB9.Ol_lZhTNTPPceylItAIVsTwLqcKFzZ7TXjEG6PAZB8s
Content-Type: application/json
